server:
  port: 9001  # 기존 포트 유지

spring:
  application:
    name: my-resource-server  # 이름 변경
  # 개발 중 임시로 데이터소스 비활성화
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shopl?useSSL=false&verifyServerCertificate=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 1234qwer!
  jpa:
    hibernate:
      ddl-auto: none  # 임시로 none 설정
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks

# 인증 서버 연동 설정
authorization-server:
  base-url: http://localhost:9000

logging:
  level:
    org.springframework.security: DEBUG  # TRACE에서 DEBUG로 조정
    org.springframework.security.oauth2: DEBUG  # OAuth2 관련 로그 추가
    org.springframework.web: TRACE
    org.springframework.web.client: DEBUG
    org.springframework.session: DEBUG
  pattern:
    console: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level [rId=%X{rId:-}] %logger{36} - %msg%n"