server:
  port: 9001  # 기존 포트 유지

spring:
  application:
    name: my-resource-server  # 이름 변경

  security:
    oauth2:
      resourceserver:
        jwt:
          # Authorization Server URI (포트 8080으로 수정)
          issuer-uri: http://localhost:9000
          # JWK Set URI (포트 8080으로 수정)
          jwk-set-uri: http://localhost:9000/oauth2/jwks

logging:
  level:
    org.springframework.security: DEBUG  # TRACE에서 DEBUG로 조정
    org.springframework.security.oauth2: DEBUG  # OAuth2 관련 로그 추가
    org.springframework.web: TRACE
    org.springframework.web.client: DEBUG
    org.springframework.session: DEBUG
  pattern:
    console: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level [rId=%X{rId:-}] %logger{36} - %msg%n"