server:
  port: ${SERVER_PORT:9000}

spring:
  application:
    name: oauth2-authorization-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shopl_authorization?useSSL=false&verifyServerCertificate=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234qwer!
  security:
    oauth2:
      client:
        registration:
          keycloak-acme:
            provider: keycloak-acme
            client-id: as-broker
            client-secret: XMAxGpivuhKxxVnoltQ2MTjhyYHW9Vqq
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, email, profile
        provider:
          keycloak-acme:
            issuer-uri: http://localhost:8081/realms/shopl-sandbox
      authorizationserver:
        issuer: ${AUTHORIZATION_SERVER_ISSUER_URL:http://localhost:${server.port}}
#  session:
#    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
  pattern:
    console: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level [rId=%X{rId:-}] %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    oauth:
      client-id: dashboard-client-1
      client-secret: secret
      realm: oauth2-realm
      app-name: OAuth2 Authorization Server
      scopes:
        - read
        - write
      use-pkce-with-authorization-code-grant: true
  show-oauth2-endpoints: false
  swagger-ui-config:
    oauth2-redirect-url: ${AUTHORIZATION_SERVER_ISSUER_URL:http://localhost:${server.port}}/swagger-ui/oauth2-redirect.html
  trim-kotlin-indent: true

app:
  resource-server:
    base-url: ${RESOURCE_SERVER_BASE_URL:http://localhost:9001}
  auth:
    redis:
      key-prefix: "app:auth:"
      idx-prefix: "app:idx:"