server:
  port: 9000

spring:
  application:
    name: oauth2-authorization-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shopl_authorization?useSSL=false&verifyServerCertificate=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 1234qwer!
  security:
    oauth2:
      client:
        keycloak-acme:
          issuer-uri: http://localhost:8081/realms/shopl-sandbox
        registration:
          keycloak-acme:
            provider: keycloak-acme
            client-id: as-broker
            client-secret: as-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, email, profile
      authorizationserver:
        issuer: http://localhost:9000
#  session:
#    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
  pattern:
    console: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level [rId=%X{rId:-}] %logger{36} - %msg%n"

springdoc:
  show-oauth2-endpoints: true
  trim-kotlin-indent: true

app:
  auth:
    redis:
      key-prefix: "app:auth:"
      idx-prefix: "app:idx:"