server:
  port: 9000

spring:
  application:
    name: oauth2-authorization-server

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
#  session:
#    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.security: TRACE
#    org.springframework.web: DEBUG
  pattern:
    console: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level [rId=%X{rId:-}] %logger{36} - %msg%n"

springdoc:
  show-oauth2-endpoints: true
  trim-kotlin-indent: true