server:
  port: 9001

spring:
  application:
    name: oauth2-client-application

  security:
    oauth2:
      client:
        registration:
          my-oauth2-server:
            client-id: oauth2-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            redirect-uri: "{baseUrl}/home"
            scope:
              - openid
              - profile
              - read
              - write
            client-name: My OAuth2 Server

        provider:
          my-oauth2-server:
            issuer-uri: http://localhost:9000
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9000/oauth2/jwks

logging:
  level:
#    org.springframework.security: TRACE
    org.springframework.web: DEBUG
  pattern:
    console: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level [rId=%X{rId:-}] %logger{36} - %msg%n"